export const typeColors: Record<string, { bg: string; text: string }> = {
  Normal:    { bg: 'bg-gray-200', text: 'text-gray-800' },
  Fire:      { bg: 'bg-orange-200', text: 'text-orange-800' },
  Water:     { bg: 'bg-blue-200', text: 'text-blue-800' },
  Electric:  { bg: 'bg-yellow-200', text: 'text-yellow-800' },
  Grass:     { bg: 'bg-green-200', text: 'text-green-800' },
  Ice:       { bg: 'bg-cyan-200', text: 'text-cyan-800' },
  Fighting:  { bg: 'bg-red-300', text: 'text-red-900' },
  Poison:    { bg: 'bg-purple-200', text: 'text-purple-800' },
  Ground:    { bg: 'bg-yellow-300', text: 'text-yellow-900' },
  Flying:    { bg: 'bg-indigo-200', text: 'text-indigo-800' },
  Psychic:   { bg: 'bg-pink-200', text: 'text-pink-800' },
  Bug:       { bg: 'bg-lime-200', text: 'text-lime-800' },
  Rock:      { bg: 'bg-yellow-400', text: 'text-yellow-900' },
  Ghost:     { bg: 'bg-violet-200', text: 'text-violet-800' },
  Dragon:    { bg: 'bg-purple-300', text: 'text-purple-900' },
  Dark:      { bg: 'bg-zinc-700', text: 'text-white' },
  Steel:     { bg: 'bg-slate-300', text: 'text-slate-900' },
  Fairy:     { bg: 'bg-rose-200', text: 'text-rose-800' },
};
